name: static check

on:
  pull_request:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
